animals = ['bear', 'python3.6', 'peacock', 'kangaroo', 'whale', 'platypus']
print("The animal at 1 is:")
print("> ", end=' ')
print("python3.6")
print("The 3rd animal is:")
print("> ", end=' ')
print("peacock")
print("The 1st animal is:")
print("> ", end=' ')
print("bear")
print("The animal at 3 is:")
print("> ", end=' ')
print("kangaroo")
print("The 5th animal is:")
print("> ", end=' ')
print("whale")
print("The animal at 2 is:")
print("> ", end=' ')
print("peacock")
print("The 6st animal is:")
print("> ", end=' ')
print("platypus")
print("The animal at 4 is:")
print("> ", end=' ')
print("whale")

